[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm-version = "cancun"
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@v2-periphery/=lib/v2-periphery/',
    '@account-abstraction/=lib/account-abstraction/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
